apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: "aekdr0wzykq9sd"
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Prometheus (alias)
    type: prometheus
    access: proxy
    orgId: 1
    uid: "cekevx0yo505cc"
    url: http://prometheus:9090
    isDefault: false
    editable: false
