{
 "title": "MLOPs - Final Project",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory_Usage_Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mem_free", "legendFormat": "{{__name__}}" },
    { "expr": "mem_buffers", "legendFormat": "{{__name__}}" },
    { "expr": "mem_cached", "legendFormat": "{{__name__}}" },
    {
     "expr": "mem_total - (mem_cached - (mem_buffers - mem_free))",
     "legendFormat": "mem_used"
    }
   ]
  },
  {
   "title": "Swap_Memory_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "swap_total", "legendFormat": "{{__name__}}" },
    { "expr": "swap_free", "legendFormat": "{{__name__}}" },
    { "expr": "swap_cached", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU_Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_avg_percent", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Resident vs Virtual Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident_mem-{{job}}" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "virtual_mem-{{job}}" }
   ]
  },
  {
   "title": "Disk Read/Write Rate of devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "io_write_rate", "legendFormat": "{{__name__}}-{{device}}" },
    { "expr": "io_read_rate", "legendFormat": "{{__name__}}-{{device}}" }
   ]
  },
  {
   "title": "HTTP request Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"backend_app\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration Vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * (\n  rate(http_request_duration_seconds_sum[1m]) \n  / \n  rate(http_request_duration_seconds_count[1m])\n)\n\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Time Usage of Python Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"backend_app\"}",
     "legendFormat": "Total_up_time_of_{{job}}"
    },
    {
     "expr": "process_cpu_seconds_total{job=\"metrics_exporter\"}",
     "legendFormat": "Total_up_time_of_{{job}}"
    }
   ]
  }
 ]
}